FROM python:3.9

WORKDIR /code

#  setup python
COPY ./pyproject.toml /code/pyproject.toml
COPY ./poetry.lock /code/poetry.lock
RUN pip install poetry
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

RUN aws --no-sign-request s3 cp s3://climatedb-dev/data-neu/newspapers.json /code/data-neu/newspapers.json

RUN aws --no-sign-request s3 cp s3://climatedb-dev/data-neu/db.sqlite /code/data-neu/db.sqlite

ENV DB_URI sqlite:////code/data-neu/db.sqlite

#  move source
COPY . /code

#  run fastapi
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
