FROM python:3.8.12
ENV DB_URI sqlite:////data-neu/db.sqlite

WORKDIR /
COPY .env pyproject.toml poetry.lock poetry.toml Makefile app.py /
COPY climatedb /climatedb
COPY static /static
COPY templates /templates
RUN make setup

#  this copy so we don't cache the s3 stuff
# COPY ./data-neu/climate-news-db-dataset.zip /data-neu/climate-news-db-dataset.zip
RUN aws --no-sign-request s3 cp s3://climatedb-dev/data-neu/newspapers.json /data-neu/newspapers.json
RUN aws --no-sign-request s3 cp s3://climatedb-dev/data-neu/db.sqlite /data-neu/db.sqlite
RUN aws --no-sign-request s3 cp s3://climatedb-dev/data-neu/climate-news-db-dataset.zip /data-neu/climate-news-db-dataset.zip

CMD ["python3", "app.py"]
