[tool.poetry]
name = "climatedb"
version = "0.3.0"
description = "A dataset of climate change newspaper articles."
authors = ["Adam Green <adam.green@adgefficiency.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Scrapy = "^2.6.1"
fastapi = "^0.75.0"
sqlmodel = "^0.0.6"
python-dotenv = "^0.20.0"
uvicorn = "^0.17.6"
pandas = "^1.4.1"
pydantic = "^1.9.0"
rich = "^12.0.1"
boto3 = "^1.21.27"
awscli = "^1.22.82"
google = "^3.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
