service: climatedb
frameworkVersion: "3"
configValidationMode: error

custom:
  name: ${self:service}-${opt:stage}
  account: ${param:account}

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-2

  environment:
    DB_URI: sqlite:////var/task/data-neu/db.sqlite

  timeout: 900

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource:
            - '*'
        - Effect: 'Allow'
          Action:
            - 'logs:*'
          Resource:
            - 'arn:aws:logs:*:*:*'
        - Effect: 'Allow'
          Action:
            - 'ec2:Start*'
            - 'ec2:Stop*'
          Resource:
            - '*'

resources:
  Resources:
    bucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:service}-${opt:stage}

    ecr:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: ${self:custom.name}

    ec2:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: pickAnImageOrUseYourOwn
        KeyName: adam-aws-may-2020.pem
        InstanceType: t2.small
        SecurityGroupIds:
          - Fn::GetAtt:
            - sg
            - GroupId
        UserData: !file userdata.sh

    sg:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: "allow ssh"
        SecurityGroupEgress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0

functions:
  controller:
    image:
      uri: ${self:custom.account}.dkr.ecr.ap-southeast-2.amazonaws.com/${self:custom.name}:latest
      command:
      - climatedb.lambda.search.handlers.search_controller
    events:
      - schedule:
          name: daily-url-search
          rate: rate(24 hours)
          input:
            s3_bucket: climatedb-dev
            s3_key: data-neu/urls.jsonl

  scraper:
    image:
      uri: ${self:custom.account}.dkr.ecr.ap-southeast-2.amazonaws.com/${self:custom.name}:latest
      command:
      - climatedb.lambda.scrape.handlers.scrape_controller
    events:
      - schedule:
          name: daily-scrape
          rate: rate(24 hours)
