service: climatedb
frameworkVersion: "3"

custom:
  name: ${self:service}-${opt:stage}
  account: ${param:account}

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-2

resources:
  Resources:
    bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${opt:stage}

    ecr:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: ${self:custom.name}

functions:
  search:
    image:
      uri: ${self:custom.account}.dkr.ecr.ap-southeast-2.amazonaws.com/${self:custom.name}:latest
      command: climatedb.lambda.handlers.search_handler
