service: climatedb
frameworkVersion: "3"
configValidationMode: error

custom:
  name: ${self:service}-${opt:stage}
  account: ${param:account}

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-2

  environment:
    S3_BUCKET: climate-news-db
    DB_URI: sqlite:////var/task/data-neu/db.sqlite
  timeout: 900

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource:
            - '*'

resources:
  Resources:
    bucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:service}-${opt:stage}

    ecr:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: ${self:custom.name}

functions:
  controller:
    image:
      uri: ${self:custom.account}.dkr.ecr.ap-southeast-2.amazonaws.com/${self:custom.name}:latest
      command: climatedb.lambda.handlers.controller_handler
    events:
      - schedule:
          name: daily-url-search
          rate: rate(24 hours)
          input:
            s3_bucket: climatedb-dev
            s3_key: data-neu/urls.jsonl
